  include Components_core;

  let rule_panel = Patterns.rule_panel;
  let modal = Patterns.modal;
  let header = Patterns.header;
  let metric_card = Patterns.metric_card;
  let log_feed = Patterns.log_feed;
  let section_title = Patterns.section_title;
  let nav_item = Patterns.nav_item;
  let message = Patterns.message;
  let timeline = Patterns.timeline;
  let composer = Patterns.composer;
  let command_bar = Patterns.command_bar;
  let footer = Patterns.footer;
  let app_shell = Patterns.app_shell;
  let wordmark = Presets.Open_code.wordmark;
  let model_status = Presets.Open_code.model_status;
  let command_block = Presets.Open_code.command_block;
  let hint_bar = Presets.Open_code.hint_bar;
  let tip = Presets.Open_code.tip;
