// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Dashboard(props) {
  let error = props.error;
  let snapshot = props.snapshot;
  let metric = (label, value, tone) => JsxRuntime.jsxs("article", {
    children: [
      JsxRuntime.jsx("div", {
        children: label,
        className: "text-sm text-zinc-400"
      }),
      JsxRuntime.jsx("div", {
        children: value,
        className: "mt-2 text-3xl font-semibold " + tone
      })
    ],
    className: "rounded-lg border border-zinc-800 bg-zinc-900 p-4"
  });
  let content;
  if (error !== undefined) {
    content = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: "Backend unavailable",
          className: "text-sm font-semibold uppercase tracking-wide text-red-300"
        }),
        JsxRuntime.jsx("p", {
          children: error,
          className: "mt-2 text-sm"
        })
      ],
      className: "rounded-lg border border-red-900 bg-red-950 p-5 text-red-100"
    });
  } else if (snapshot !== undefined) {
    let value = snapshot.lastError;
    let tmp = value === "" ? null : JsxRuntime.jsx("div", {
        children: value,
        className: "mt-5 rounded-lg border border-amber-800 bg-amber-950 p-4 text-sm text-amber-100"
      });
    let match = snapshot.issues.length;
    content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            metric("Running", snapshot.running, "text-sky-200"),
            metric("Retrying", snapshot.retrying, "text-amber-200"),
            metric("Total tokens", snapshot.tokens, "text-emerald-200")
          ],
          className: "grid gap-4 sm:grid-cols-3"
        }),
        tmp,
        JsxRuntime.jsxs("section", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  children: "Project issues",
                  className: "text-sm font-medium text-zinc-200"
                }),
                JsxRuntime.jsx("div", {
                  children: snapshot.issues.length.toString() + " tracked",
                  className: "text-xs text-zinc-500"
                })
              ],
              className: "flex items-center justify-between border-b border-zinc-800 px-4 py-3"
            }),
            match !== 0 ? JsxRuntime.jsx("div", {
                children: snapshot.issues.map(issue => JsxRuntime.jsxs("article", {
                  children: [
                    JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("span", {
                              children: issue.identifier,
                              className: "rounded-md border border-sky-800 bg-sky-950 px-2 py-0.5 text-xs font-medium text-sky-200"
                            }),
                            JsxRuntime.jsx("h2", {
                              children: issue.title,
                              className: "text-sm font-semibold text-zinc-100"
                            })
                          ],
                          className: "flex flex-wrap items-center gap-2"
                        }),
                        JsxRuntime.jsx("p", {
                          children: issue.description,
                          className: "mt-2 max-w-3xl text-sm leading-6 text-zinc-400"
                        })
                      ],
                      className: "min-w-0"
                    }),
                    JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("span", {
                        children: issue.state,
                        className: "rounded-md border border-emerald-800 bg-emerald-950 px-2.5 py-1 text-xs font-medium text-emerald-200"
                      }),
                      className: "flex items-start md:justify-end"
                    })
                  ],
                  className: "grid gap-3 px-4 py-4 md:grid-cols-[minmax(0,1fr)_auto]"
                })),
                className: "divide-y divide-zinc-800"
              }) : JsxRuntime.jsx("div", {
                children: "No project issues were returned by the latest poll.",
                className: "p-4 text-sm text-zinc-400"
              })
          ],
          className: "mt-6 rounded-lg border border-zinc-800 bg-zinc-900"
        }),
        JsxRuntime.jsxs("section", {
          children: [
            JsxRuntime.jsx("div", {
              children: "Runtime Snapshot",
              className: "border-b border-zinc-800 px-4 py-3 text-sm font-medium text-zinc-200"
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("div", {
                      children: "Generated",
                      className: "text-xs uppercase text-zinc-500"
                    }),
                    JsxRuntime.jsx("div", {
                      children: snapshot.generatedAt,
                      className: "mt-1 text-sm text-zinc-200"
                    })
                  ],
                  className: "rounded-md bg-zinc-950 p-4"
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("div", {
                      children: "Tracker",
                      className: "text-xs uppercase text-zinc-500"
                    }),
                    JsxRuntime.jsx("div", {
                      children: "GitHub Issues and GitHub Projects",
                      className: "mt-1 text-sm text-zinc-200"
                    })
                  ],
                  className: "rounded-md bg-zinc-950 p-4"
                })
              ],
              className: "grid gap-4 p-4 md:grid-cols-2"
            })
          ],
          className: "mt-6 rounded-lg border border-zinc-800 bg-zinc-900"
        })
      ]
    });
  } else {
    content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            metric("Running", "-", "text-zinc-100"),
            metric("Retrying", "-", "text-zinc-100"),
            metric("Tokens", "-", "text-zinc-100")
          ],
          className: "grid gap-4 sm:grid-cols-3"
        }),
        JsxRuntime.jsx("div", {
          children: "Loading runtime state...",
          className: "mt-6 rounded-lg border border-zinc-800 bg-zinc-900 p-6 text-zinc-300"
        })
      ]
    });
  }
  return JsxRuntime.jsxs("section", {
    children: [
      JsxRuntime.jsx("header", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                  children: "Personal Symphony",
                  className: "text-xl font-semibold tracking-normal"
                }),
                JsxRuntime.jsx("p", {
                  children: "GitHub Issues + Projects orchestration",
                  className: "text-sm text-zinc-400"
                })
              ]
            }),
            JsxRuntime.jsx("span", {
              children: "OCaml API",
              className: "rounded-md border border-emerald-700/60 bg-emerald-950 px-3 py-1 text-xs font-medium text-emerald-200"
            })
          ],
          className: "mx-auto flex max-w-6xl items-center justify-between px-5 py-4"
        }),
        className: "border-b border-zinc-800 bg-zinc-950/95"
      }),
      JsxRuntime.jsx("div", {
        children: content,
        className: "mx-auto max-w-6xl px-5 py-6"
      })
    ],
    className: "min-h-screen bg-zinc-950 text-zinc-100"
  });
}

let make = Dashboard;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
