// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Dashboard(props) {
  let error = props.error;
  let snapshot = props.snapshot;
  let metric = (label, value, tone) => JsxRuntime.jsxs("article", {
    children: [
      JsxRuntime.jsx("div", {
        children: label,
        className: "text-sm text-zinc-400"
      }),
      JsxRuntime.jsx("div", {
        children: value,
        className: "mt-2 text-3xl font-semibold " + tone
      })
    ],
    className: "rounded-lg border border-zinc-800 bg-zinc-900 p-4"
  });
  let issueStateColumns = issues => {
    let states = [];
    for (let i = 0, i_finish = issues.length; i < i_finish; ++i) {
      let issue = issues[i];
      if (issue !== undefined && !states.includes(issue.state)) {
        states.push(issue.state);
      }
    }
    return states;
  };
  let content;
  if (error !== undefined) {
    content = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: "Backend unavailable",
          className: "text-sm font-semibold uppercase tracking-wide text-red-300"
        }),
        JsxRuntime.jsx("p", {
          children: error,
          className: "mt-2 text-sm"
        })
      ],
      className: "rounded-lg border border-red-900 bg-red-950 p-5 text-red-100"
    });
  } else if (snapshot !== undefined) {
    let value = snapshot.lastError;
    let tmp = value === "" ? null : JsxRuntime.jsx("div", {
        children: value,
        className: "mt-5 rounded-lg border border-amber-800 bg-amber-950 p-4 text-sm text-amber-100"
      });
    let match = snapshot.issues.length;
    content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            metric("Running", snapshot.running, "text-sky-200"),
            metric("Retrying", snapshot.retrying, "text-amber-200"),
            metric("Total tokens", snapshot.tokens, "text-emerald-200")
          ],
          className: "grid gap-4 sm:grid-cols-3"
        }),
        tmp,
        JsxRuntime.jsx("section", {
          children: JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Generated",
                    className: "text-xs uppercase text-zinc-500"
                  }),
                  JsxRuntime.jsx("div", {
                    children: snapshot.generatedAt,
                    className: "mt-1 text-sm text-zinc-200"
                  })
                ]
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  "State API: ",
                  JsxRuntime.jsx("code", {
                    children: "/api/v1/state",
                    className: "text-sky-200"
                  })
                ],
                className: "text-sm text-zinc-400"
              })
            ],
            className: "grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end"
          }),
          className: "mb-6 mt-5 max-w-xl rounded-lg border border-zinc-800 bg-zinc-900 px-4 py-3"
        }),
        JsxRuntime.jsxs("section", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  children: "Project board",
                  className: "text-sm font-medium text-zinc-200"
                }),
                JsxRuntime.jsx("div", {
                  children: snapshot.issues.length.toString() + " tracked",
                  className: "text-xs text-zinc-500"
                })
              ],
              className: "flex items-center justify-between border-b border-zinc-800 px-4 py-3"
            }),
            match !== 0 ? JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("div", {
                  children: issueStateColumns(snapshot.issues).map(state => {
                    let stateIssues = snapshot.issues.filter(issue => issue.state === state);
                    return JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("h2", {
                              children: state,
                              className: "text-sm font-semibold text-zinc-100"
                            }),
                            JsxRuntime.jsx("span", {
                              children: stateIssues.length.toString(),
                              className: "rounded-md border border-zinc-700 px-2 py-0.5 text-xs text-zinc-400"
                            })
                          ],
                          className: "flex items-center justify-between border-b border-zinc-800 px-3 py-2.5"
                        }),
                        JsxRuntime.jsx("div", {
                          children: stateIssues.map(issue => JsxRuntime.jsxs("article", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx("span", {
                                    children: issue.identifier,
                                    className: "rounded-md border border-sky-800 bg-sky-950 px-2 py-0.5 text-xs font-medium text-sky-200"
                                  }),
                                  JsxRuntime.jsx("span", {
                                    children: "read-only",
                                    className: "text-xs text-zinc-500"
                                  })
                                ],
                                className: "flex flex-wrap items-center gap-2"
                              }),
                              JsxRuntime.jsx("h3", {
                                children: issue.title,
                                className: "mt-2 text-sm font-semibold leading-5 text-zinc-100"
                              }),
                              JsxRuntime.jsx("p", {
                                children: issue.description,
                                className: "mt-2 line-clamp-4 text-sm leading-6 text-zinc-400"
                              })
                            ],
                            className: "rounded-md border border-zinc-800 bg-zinc-900 p-3"
                          })),
                          className: "space-y-3 p-3"
                        })
                      ],
                      className: "min-h-48 rounded-lg border border-zinc-800 bg-zinc-950"
                    });
                  }),
                  className: "grid min-w-[760px] auto-cols-[minmax(240px,1fr)] grid-flow-col gap-4"
                }),
                className: "overflow-x-auto p-4"
              }) : JsxRuntime.jsx("div", {
                children: "No project issues were returned by the latest poll.",
                className: "p-4 text-sm text-zinc-400"
              })
          ],
          className: "mt-6 rounded-lg border border-zinc-800 bg-zinc-900"
        })
      ]
    });
  } else {
    content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            metric("Running", "-", "text-zinc-100"),
            metric("Retrying", "-", "text-zinc-100"),
            metric("Tokens", "-", "text-zinc-100")
          ],
          className: "grid gap-4 sm:grid-cols-3"
        }),
        JsxRuntime.jsx("div", {
          children: "Loading runtime state...",
          className: "mt-6 rounded-lg border border-zinc-800 bg-zinc-900 p-6 text-zinc-300"
        })
      ]
    });
  }
  return JsxRuntime.jsxs("section", {
    children: [
      JsxRuntime.jsx("header", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                  children: "Personal Symphony",
                  className: "text-xl font-semibold tracking-normal"
                }),
                JsxRuntime.jsx("p", {
                  children: "GitHub Issues + Projects orchestration",
                  className: "text-sm text-zinc-400"
                })
              ]
            }),
            JsxRuntime.jsx("span", {
              children: "OCaml API",
              className: "rounded-md border border-emerald-700/60 bg-emerald-950 px-3 py-1 text-xs font-medium text-emerald-200"
            })
          ],
          className: "mx-auto flex max-w-6xl items-center justify-between px-5 py-4"
        }),
        className: "border-b border-zinc-800 bg-zinc-950/95"
      }),
      JsxRuntime.jsx("div", {
        children: content,
        className: "mx-auto max-w-6xl px-5 py-6"
      })
    ],
    className: "min-h-screen bg-zinc-950 text-zinc-100"
  });
}

let make = Dashboard;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
