// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dashboard from "./Dashboard.res.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import "./styles.css";
;

function shortDescription(value) {
  const text = String(value || "").replace(/\s+/g, " ").trim();
  if (!text) return "No description provided.";
  return text.length > 180 ? text.slice(0, 177) + "..." : text;
}
;

function readinessText(state) {
  if (state.readiness_gaps.length !== 0) {
    return "Readiness Gaps: " + state.readiness_gaps.map(gap => gap.requirement + ": " + gap.remediation).join("; ");
  } else {
    return "";
  }
}

function taskErrorForIssue(state, issueId) {
  let error = state.issue_errors.find(error => error.issue_id === issueId);
  if (error !== undefined) {
    return error.error;
  }
  let error$1 = state.retrying.find(error => error.issue_id === issueId);
  if (error$1 === undefined) {
    return "";
  }
  let message = error$1.error;
  if (message !== undefined) {
    return message;
  } else {
    return "";
  }
}

function renderDashboard(root, snapshot, error) {
  root.render(JsxRuntime.jsx(Dashboard.make, {
    snapshot: snapshot,
    error: error
  }));
}

function snapshotFromState(state) {
  return {
    running: state.counts.running.toString(),
    retrying: state.counts.retrying.toString(),
    tokens: state.codex_totals.total_tokens.toString(),
    generatedAt: state.generated_at,
    lastError: readinessText(state),
    issues: state.issues.map(issue => {
      let value = issue.description;
      let description = value !== undefined ? value : "";
      return {
        identifier: issue.issue_identifier,
        title: issue.title,
        state: issue.state,
        description: shortDescription(description),
        error: taskErrorForIssue(state, issue.issue_id)
      };
    })
  };
}

function loadState(root, latestSnapshot, isLoading) {
  if (isLoading.contents) {
    return;
  }
  isLoading.contents = true;
  let promise = fetch("/api/v1/state", {
    headers: {
      Accept: "application/json"
    }
  });
  let promise$1 = promise.then(response => {
    if (response.ok) {
      return response.json();
    } else {
      return Promise.reject(new Error("HTTP " + response.status.toString()));
    }
  });
  let promise$2 = promise$1.then(state => {
    let snapshot = snapshotFromState(state);
    isLoading.contents = false;
    latestSnapshot.contents = snapshot;
    renderDashboard(root, snapshot, undefined);
  });
  promise$2.catch(_error => {
    isLoading.contents = false;
    let message = _error.message;
    let message$1 = (message == null) ? "Unable to load state" : message;
    renderDashboard(root, latestSnapshot.contents, message$1);
  });
}

let element = document.getElementById("root");

if (!(element == null)) {
  let root = Client.createRoot(element);
  let latestSnapshot = {
    contents: undefined
  };
  let isLoading = {
    contents: false
  };
  renderDashboard(root, undefined, undefined);
  loadState(root, latestSnapshot, isLoading);
  setInterval(() => loadState(root, latestSnapshot, isLoading), 5000);
}

export {
  readinessText,
  taskErrorForIssue,
  renderDashboard,
  snapshotFromState,
  loadState,
}
/*  Not a pure module */
