// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dashboard from "./Dashboard.res.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import "./styles.css";
;

function shortDescription(value) {
  const text = String(value || "").replace(/\s+/g, " ").trim();
  if (!text) return "No description provided.";
  return text.length > 180 ? text.slice(0, 177) + "..." : text;
}
;

function readinessText(state) {
  if (state.readiness_gaps.length !== 0) {
    return "Readiness Gaps: " + state.readiness_gaps.map(gap => gap.requirement + ": " + gap.remediation).join("; ");
  }
  let message = state.last_error;
  if (message !== undefined) {
    return message;
  } else {
    return "";
  }
}

function renderDashboard(root, snapshot, error) {
  root.render(JsxRuntime.jsx(Dashboard.make, {
    snapshot: snapshot,
    error: error
  }));
}

function loadState(root) {
  renderDashboard(root, undefined, undefined);
  let promise = fetch("/api/v1/state", {
    headers: {
      Accept: "application/json"
    }
  });
  let promise$1 = promise.then(response => {
    if (response.ok) {
      return response.json();
    } else {
      return Promise.reject(new Error("HTTP " + response.status.toString()));
    }
  });
  let promise$2 = promise$1.then(state => {
    renderDashboard(root, {
      running: state.counts.running.toString(),
      retrying: state.counts.retrying.toString(),
      tokens: state.codex_totals.total_tokens.toString(),
      generatedAt: state.generated_at,
      lastError: readinessText(state),
      issues: state.issues.map(issue => {
        let value = issue.description;
        let description = value !== undefined ? value : "";
        return {
          identifier: issue.issue_identifier,
          title: issue.title,
          state: issue.state,
          description: shortDescription(description)
        };
      })
    }, undefined);
  });
  promise$2.catch(_error => {
    let message = _error.message;
    let message$1 = (message == null) ? "Unable to load state" : message;
    renderDashboard(root, undefined, message$1);
  });
}

let element = document.getElementById("root");

if (!(element == null)) {
  let root = Client.createRoot(element);
  loadState(root);
  setInterval(() => loadState(root), 5000);
}

export {
  readinessText,
  renderDashboard,
  loadState,
}
/*  Not a pure module */
