// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dashboard from "./Dashboard.res.js";
import * as LiveStateJs from "./liveState.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import "./styles.css";
;

function shortDescription(value) {
  const text = String(value || "").replace(/\s+/g, " ").trim();
  if (!text) return "No description provided.";
  return text.length > 180 ? text.slice(0, 177) + "..." : text;
}
function arrayOrEmpty(value) {
  return Array.isArray(value) ? value : [];
}
;

function connectLiveState(prim0, prim1) {
  LiveStateJs.connectLiveState(prim0, prim1);
}

function readinessText(state) {
  if (arrayOrEmpty(state.readiness_gaps).length !== 0) {
    return "Readiness Gaps: " + arrayOrEmpty(state.readiness_gaps).map(gap => gap.requirement + ": " + gap.remediation).join("; ");
  } else {
    return "";
  }
}

function taskErrorForIssue(state, issueId) {
  let error = arrayOrEmpty(state.issue_errors).find(error => error.issue_id === issueId);
  if (error !== undefined) {
    return error.error;
  }
  let error$1 = arrayOrEmpty(state.retrying).find(error => error.issue_id === issueId);
  if (error$1 === undefined) {
    return "";
  }
  let message = error$1.error;
  if (message !== undefined) {
    return message;
  } else {
    return "";
  }
}

function renderDashboard(root, snapshot, error) {
  root.render(JsxRuntime.jsx(Dashboard.make, {
    snapshot: snapshot,
    error: error
  }));
}

function snapshotFromState(state) {
  return {
    running: state.counts.running.toString(),
    retrying: state.counts.retrying.toString(),
    tokens: state.codex_totals.total_tokens.toString(),
    generatedAt: state.generated_at,
    lastError: readinessText(state),
    statusOrder: arrayOrEmpty(state.status_order),
    issues: arrayOrEmpty(state.issues).map(issue => {
      let value = issue.description;
      let description = value !== undefined ? value : "";
      let value$1 = issue.url;
      return {
        identifier: issue.issue_identifier,
        title: issue.title,
        state: issue.state,
        url: value$1 !== undefined ? value$1 : "",
        description: shortDescription(description),
        error: taskErrorForIssue(state, issue.issue_id)
      };
    })
  };
}

let element = document.getElementById("root");

if (!(element == null)) {
  let root = Client.createRoot(element);
  let latestSnapshot = {
    contents: undefined
  };
  renderDashboard(root, undefined, undefined);
  LiveStateJs.connectLiveState(state => {
    let snapshot = snapshotFromState(state);
    latestSnapshot.contents = snapshot;
    renderDashboard(root, snapshot, undefined);
  }, message => renderDashboard(root, latestSnapshot.contents, message));
}

export {
  connectLiveState,
  readinessText,
  taskErrorForIssue,
  renderDashboard,
  snapshotFromState,
}
/*  Not a pure module */
